# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and test on push to any branch

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Pull source
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Display dotnet version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore XExpressions.sln

    - name: Build XExpressions
      run: dotnet build XExpressions.sln --no-restore
     
    - name: Test Variant
      run: dotnet test XExpressions.VariantType.Tests --no-build --verbosity normal

    - name: Test Expressions
      run: dotnet test XExpressions.Tests --no-build --verbosity normal
     
    - name: Bump build version
      id: bump
      uses: vers-one/dotnet-project-version-updater@v1.3
      with:
        file: |
          "**/XExpressions.csproj", "**/XExpressions.VariantType.csproj"
        version: bump-revision

#    - run: |
#        git config user.name "test"
#        git config user.email "richard-mcintyre@users.noreply.github.com"
#        git add .
#        git commit -m "Bump project version to ${{ steps.bump.outputs.newVersion }}"
#        git push
          
      
    - name: Create package
      run: dotnet pack -o dist -c PackRelease XExpressions


#    - name: Add publish source
#      run: dotnet nuget add source --username richard-mcintyre --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/richard-mcintyre/index.json"
#    - name: Push package to nuget
#      run: dotnet nuget push "dist/XExpressions.1.0.0.nupkg" --api-key ${{secrets.NUGET_API_TOKEN}} --source https://api.nuget.org/v3/index.json
