# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and publish

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Pull source
      uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore XExpressions.sln

    - name: Build XExpressions
      run: dotnet build XExpressions.sln --no-restore
     
    - name: Test Variant
      run: dotnet test XExpressions.VariantType.Tests --no-build --verbosity normal

    - name: Test Expressions
      run: dotnet test XExpressions.Tests --no-build --verbosity normal
     
    - name: Bump build version
      id: bump
      uses: vers-one/dotnet-project-version-updater@v1.3
      with:
        file: |
          "**/XExpressions.csproj", "**/XExpressions.VariantType.csproj"
        version: bump-revision
      
    - name: Create package
      run: dotnet pack -o dist -c PackRelease XExpressions

    - name: Create package variant
      run: dotnet pack -o dist -c PackRelease XExpressions.VariantType

    - name: Upload package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages.zip
        path: dist